#!/usr/bin/env bash
# Build release zips under dist/ — generic Octava (octavawms/) or white-label Izprati (izpratibg/).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
MODULE="octava"
OUT=""
PLUGIN_SLUG=""

function usage() {
	echo "Usage: $(basename "$0") [-m octava|izpratibg] [-o PATH]"
	echo ""
	echo "  -m octava     dist/octavawms.zip, folder octavawms/ (default)"
	echo "  -m izpratibg  dist/izpratibg.zip, folder izpratibg/, stamps OCTAVA_WOO_PARTNER_MODULE"
	echo "  -o PATH       Output zip path"
}

while getopts "hm:o:" opt; do
	case "$opt" in
		h)
			usage
			exit 0
			;;
		m)
			MODULE=$OPTARG
			;;
		o)
			OUT=$OPTARG
			;;
		*)
			usage >&2
			exit 1
			;;
	esac
done

case "$MODULE" in
	octava)
		PLUGIN_SLUG="${PLUGIN_SLUG:-octavawms}"
		OUT="${OUT:-${ROOT}/dist/${PLUGIN_SLUG}.zip}"
		;;
	izpratibg)
		PLUGIN_SLUG="${PLUGIN_SLUG:-izpratibg}"
		OUT="${OUT:-${ROOT}/dist/izpratibg.zip}"
		;;
	*)
		echo "❌ Unknown -m '$MODULE' (use octava or izpratibg)" >&2
		exit 1
		;;
esac

if ! command -v rsync >/dev/null || ! command -v zip >/dev/null; then
	echo "❌ Requires rsync and zip in PATH." >&2
	exit 1
fi

STAGE="$(mktemp -d)"
trap 'rm -rf "${STAGE}"' EXIT

TARGET="${STAGE}/${PLUGIN_SLUG}"
mkdir -p "${TARGET}"

rsync -a \
	"${ROOT}/" "${TARGET}/" \
	--exclude='.cursor/' \
	--exclude='.git/' \
	--exclude='.vscode/' \
	--exclude='.phpunit.cache/' \
	--exclude='dist/' \
	--exclude='scripts/' \
	--exclude='dev/' \
	--exclude='vendor/' \
	--exclude='tests/' \
	--exclude='docs/' \
	--exclude='.DS_Store' \
	--exclude='.gitignore' \
	--exclude='.gitkeep' \
	--exclude='phpunit.xml.dist' \
	--exclude='composer.lock' \
	--exclude='release.sh' \
	--exclude='AGENTS.md' \
	--exclude='partner-build.generated.php'

if [ "$MODULE" = "izpratibg" ]; then
	cat >"${TARGET}/partner-build.generated.php" <<'GENPHP'
<?php
// Generated by scripts/package-release.sh — do not edit.
if (! defined('OCTAVA_WOO_PARTNER_MODULE')) {
	define('OCTAVA_WOO_PARTNER_MODULE', 'izpratibg');
}
GENPHP
fi

mkdir -p "$(dirname "${OUT}")"
TMP_ZIP="${STAGE}/$(basename "${OUT}")"
(
	cd "${STAGE}"
	zip -r -q "${TMP_ZIP}" "${PLUGIN_SLUG}"
)
mv "${TMP_ZIP}" "${OUT}"

echo "✅ $(basename "${OUT}") ($(wc -c <"${OUT}" | tr -d ' ') bytes)"
